### ISSUE TITLE
Pack is ignored when Force Unicode Font = true

### ISSUE THREAD

**Issue by Mg138** [Androkai/AndrosDiscordEmojis#1]
(I do not fully understand how Minecraft resource packs work.)
When Force Unicode Font is set to true, the pack is completely ignored, and the tofu block we all love would appear.

**Comment by Androkai** [comment]
Enabling "Force Unicode Font" results in using the old deprecated font format which does not support the full Unicode range added with 1.16 and so not the emojis added in this pack. Do you have a reason to still use it?

**Comment by Mg138** [comment]
Some people are used to the unicode font, as there were now fixed bugs where bold Chinese text would break without enabling Force Unicode Font.

Is there not a way to make it so that enabling Force Unicode Font does no effect?
Like forcing Minecraft not to use the unicode font with the pack installed?

**Comment by Androkai** [comment]
As far as I can see, the old fonts system was not extended anymore, so it definitely does not support emojis, because the later Unicode tables are missing (and also adding them does nothing, because they are not recognized/processed by the program). 

At the current state there also seems to be no way for a resource or data pack to enforce the player's setting on this. So sadly nothing me or you can do to enforce it server side. Requires at least a client side mod but then you can also just tell your players to disable it.

Since there is currently no way to solve this and you already agreed to, I'm closing this ticket. Thx for the report, will at least add this information to the documentation. 👍
