### ISSUE TITLE
Can I make an updated version of this resource pack using newer emojis?

### ISSUE THREAD

**Issue by Terminxa** [Androkai/AndrosDiscordEmojis#4]
I would give credit ofc but seeing as this pack hasnt been updated in awhile I wanted to ask if it was ok if i could make an updated version.

**Comment by Androkai** [comment]
For sure! Feel free to fork and change to your preferences. Since I'm using [Twemoji](https://twemoji.twitter.com/) emojies here which are licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) I used the same license for convenience. GitHub provides a summary to this type of license on the [license page](https://github.com/Androkai/AndrosDiscordEmojis/blob/master/LICENSE) of this project stating what's allowed and what not. As long as you give credits to the original work, name it's license and mark the changes you've made, you can do almost anything you want and publish it yourself.

You can also open a pull request afterwards if you like. However, I'm a little strict with the quality of what I accept in terms of the size and quality of the images. Feel free to check out my comment on the already open pull request #3 about this.

**Comment by Terminxa** [comment]
I forgot to put it here, but I released the pack on Modrinth. https://modrinth.com/resourcepack/twemoji-visibility

**Comment by Androkai** [comment]
Thanks for the quick info.👍 Glad you were able to successfully update the pack.
